easy_admin:
    site_name: mailserver-admin
    design:
        menu:
            - { entity: 'Domain', icon: 'globe' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Alias', icon: 'list-alt' }
            - { label: 'Other' }
            - { label: 'DKIM', route: 'app_dkim_index', icon: 'shield' }

    user:
        display_name: true
        display_avatar: false

    entities:
        Domain:
            class: App\Entity\Domain
            list:
                sort: ['name', 'ASC']
                fields:
                    - { property: 'name' }
                    - { property: 'aliases' }
                    - { property: 'users' }
            form:
                fields:
                    - { property: 'name' }

        User:
            class: App\Entity\User
            list:
                sort: ['domain.name', 'ASC']
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'enabled' }
                    - { property: 'sendOnly' }
                    - { property: 'admin' }
            form:
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'admin' }
                    - { property: 'enabled' }
                    - { property: 'sendOnly', help: 'send only accounts are not allowed to receive mails' }
                    - { property: 'quota', help: 'how much space the account can use (in megabytes)' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }

        Alias:
            class: App\Entity\Alias
            list:
                sort: ['domain.name', 'ASC']
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'destination', type: 'email' }
            form:
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'destination', type: 'email' }
