easy_admin:
    site_name: mailserver-admin
    design:
        menu:
            - { entity: 'Domain', icon: 'globe' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Alias', icon: 'list-alt' }
            - { label: 'Other' }
            - { entity: 'DKIM', icon: 'shield' }

    user:
        display_name: true
        display_avatar: false

    entities:
        Domain:
            class: App\Entity\Domain
            list:
                sort: ['name', 'ASC']
                fields:
                    - { property: 'name' }
                    - { property: 'aliases' }
                    - { property: 'users' }
            form:
                fields:
                    - { property: 'name' }

        User:
            class: App\Entity\User
            list:
                sort: ['domain.name', 'ASC']
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'enabled' }
                    - { property: 'sendOnly' }
                    - { property: 'admin' }
            form:
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'admin' }
                    - { property: 'enabled' }
                    - { property: 'sendOnly', help: 'send only accounts are not allowed to receive mails' }
                    - { property: 'quota', help: 'how much space the account can use (in megabytes)' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }

        Alias:
            class: App\Entity\Alias
            list:
                sort: ['domain.name', 'ASC']
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'destination', type: 'email' }
            form:
                fields:
                    - { property: 'domain' }
                    - { property: 'name', type: 'text' }
                    - { property: 'destination', type: 'email' }

        DKIM:
            class: App\Entity\Domain
            templates:
                edit: 'admin/dkim/edit.html.twig'
            list:
                sort: ['name', 'ASC']
                actions:
                    - '-delete'
                    - '-new'
                    - 'edit'
                    - { name: 'app_dkim_recreate', type: 'route', label: 'Recreate Private Key' }
                fields:
                    - { property: 'name', label: 'Domain' }
                    - { property: 'dkimEnabled', label: 'Enabled' }
                    - { property: 'dkimStatus.dkimRecordFound', label: 'Domain Key found', type: 'boolean' }
                    - { property: 'dkimStatus.dkimRecordValid', label: 'Key valid', type: 'boolean' }

            form:
                help: If you enable DKIM for this domain, all outgoing mails will have a DKIM signature attached. You should set up the DNS record before doing this. After you have generated a private key, a DNS record is provided that needs to be added to your domain's zone.
                actions:
                    - '-delete'
                fields:
                    - { property: 'name', label: 'Domain', type_options: { disabled: true }}
                    - { property: 'dkimEnabled', label: 'Enabled' }
                    - { property: 'dkimSelector', label: 'Selector', help: 'Usually the current year' }
