framework:
    secret: '%env(APP_SECRET)%'
    session: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
