<?php

declare(strict_types=1);
/**
 * This file is part of the mailserver-admin package.
 * (c) Jeffrey Boehm <https://github.com/jeboehm/mailserver-admin>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Bootstraps a fresh installation on either platform.
 *
 * The migrations preceding this one describe the history of a MySQL schema that
 * started out as a pre-2018 "virtual_*" schema. They only apply to installations
 * that actually carry that history; everything else arrives here with an empty
 * database and gets the current schema in one go.
 *
 * Generated with "doctrine:schema:create --dump-sql" per platform so it matches
 * the mapping exactly; regenerate the same way rather than editing statements by
 * hand.
 */
final class Version20260212000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline schema for fresh installations';
    }

    public function up(Schema $schema): void
    {
        // Installations carrying the MySQL history already have the schema.
        if ($schema->hasTable('mail_domains')) {
            return;
        }

        if ($this->platform instanceof AbstractMySQLPlatform) {
            $this->addSql(
                'CREATE TABLE mail_domains (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, dkim_enabled TINYINT NOT NULL, dkim_selector VARCHAR(255) NOT NULL, dkim_private_key LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_56C63EF25E237E06 (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`'
            );
            $this->addSql(
                'CREATE TABLE mail_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, `admin` TINYINT NOT NULL, domain_admin TINYINT NOT NULL, enabled TINYINT NOT NULL, send_only TINYINT NOT NULL, quota INT NOT NULL, domain_id INT DEFAULT NULL, INDEX IDX_20400786115F0EE5 (domain_id), UNIQUE INDEX user_idx (name, domain_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`'
            );
            $this->addSql(
                'CREATE TABLE mail_aliases (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, destination VARCHAR(255) NOT NULL, domain_id INT DEFAULT NULL, INDEX IDX_85AF3A56115F0EE5 (domain_id), UNIQUE INDEX alias_idx (domain_id, name, destination), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`'
            );
            $this->addSql(
                'CREATE TABLE fetchmail_accounts (id INT AUTO_INCREMENT NOT NULL, config_host VARCHAR(255) NOT NULL, config_protocol VARCHAR(50) NOT NULL, config_port SMALLINT NOT NULL, config_username VARCHAR(255) NOT NULL, config_password VARCHAR(255) NOT NULL, config_ssl TINYINT NOT NULL, config_verify_ssl TINYINT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_F61C5867A76ED395 (user_id), UNIQUE INDEX host_username_idx (config_host, config_username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`'
            );

            $this->addSql(
                'ALTER TABLE mail_users ADD CONSTRAINT FK_20400786115F0EE5 FOREIGN KEY (domain_id) REFERENCES mail_domains (id)'
            );
            $this->addSql(
                'ALTER TABLE mail_aliases ADD CONSTRAINT FK_85AF3A56115F0EE5 FOREIGN KEY (domain_id) REFERENCES mail_domains (id)'
            );
            $this->addSql(
                'ALTER TABLE fetchmail_accounts ADD CONSTRAINT FK_F61C5867A76ED395 FOREIGN KEY (user_id) REFERENCES mail_users (id)'
            );

            return;
        }

        if (!$this->platform instanceof PostgreSQLPlatform) {
            return;
        }

        $this->addSql(
            'CREATE TABLE mail_domains (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, dkim_enabled BOOLEAN NOT NULL, dkim_selector VARCHAR(255) NOT NULL, dkim_private_key TEXT NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_56C63EF25E237E06 ON mail_domains (name)');

        $this->addSql(
            'CREATE TABLE mail_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, admin BOOLEAN NOT NULL, domain_admin BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, send_only BOOLEAN NOT NULL, quota INT NOT NULL, domain_id INT DEFAULT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX IDX_20400786115F0EE5 ON mail_users (domain_id)');
        $this->addSql('CREATE UNIQUE INDEX user_idx ON mail_users (name, domain_id)');

        $this->addSql(
            'CREATE TABLE mail_aliases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, destination VARCHAR(255) NOT NULL, domain_id INT DEFAULT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX IDX_85AF3A56115F0EE5 ON mail_aliases (domain_id)');
        $this->addSql('CREATE UNIQUE INDEX alias_idx ON mail_aliases (domain_id, name, destination)');

        $this->addSql(
            'CREATE TABLE fetchmail_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, config_host VARCHAR(255) NOT NULL, config_protocol VARCHAR(50) NOT NULL, config_port SMALLINT NOT NULL, config_username VARCHAR(255) NOT NULL, config_password VARCHAR(255) NOT NULL, config_ssl BOOLEAN NOT NULL, config_verify_ssl BOOLEAN NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX IDX_F61C5867A76ED395 ON fetchmail_accounts (user_id)');
        $this->addSql('CREATE UNIQUE INDEX host_username_idx ON fetchmail_accounts (config_host, config_username)');

        $this->addSql(
            'ALTER TABLE mail_users ADD CONSTRAINT FK_20400786115F0EE5 FOREIGN KEY (domain_id) REFERENCES mail_domains (id)'
        );
        $this->addSql(
            'ALTER TABLE mail_aliases ADD CONSTRAINT FK_85AF3A56115F0EE5 FOREIGN KEY (domain_id) REFERENCES mail_domains (id)'
        );
        $this->addSql(
            'ALTER TABLE fetchmail_accounts ADD CONSTRAINT FK_F61C5867A76ED395 FOREIGN KEY (user_id) REFERENCES mail_users (id)'
        );
    }

    public function down(Schema $schema): void
    {
        if (!$schema->hasTable('mail_domains')) {
            return;
        }

        // Children first, so the foreign keys go away with their tables.
        $this->addSql('DROP TABLE fetchmail_accounts');
        $this->addSql('DROP TABLE mail_aliases');
        $this->addSql('DROP TABLE mail_users');
        $this->addSql('DROP TABLE mail_domains');
    }
}
